name: Build and push Docker image

on:
  push:
    branches: [ master ]

env:
  DOCKER_USERNAME: azizprog
  DOCKER_PASSWORD: Ab07121564!

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t azizprog/tailwind_page:${{ github.sha }} .
      - name: Push Docker image
        run: |
          docker login -u azizprog -p Ab07121564!
          docker push azizprog/tailwind_page:${{ github.sha }}
